### ISSUE TITLE
[Crash] Crash on sign out

### ISSUE THREAD

**Issue by bmarty** [element-hq/element-x-android#1292]
Not always reproduced:

```
Thread: main, Exception: java.lang.IllegalStateException: NotificationSettings object has already been destroyed
at org.matrix.rustcomponents.sdk.NotificationSettings.setDelegate(matrix_sdk_ffi.kt:18281)
at io.element.android.libraries.matrix.impl.RustMatrixClient.close(RustMatrixClient.kt:291)
at io.element.android.libraries.matrix.impl.RustMatrixClient$doLogout$2.invokeSuspend(RustMatrixClient.kt:323)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
```

**Comment by bmarty** [comment]
Nor reproduced since a while.
