### ISSUE TITLE
Selecting ntfy as notification provider does not work

### ISSUE THREAD

**Issue by Xiretza** [element-hq/element-x-android#2895]
### Steps to reproduce

1. In "Advanced settings", tap "Push notification provider"
2. From the selection of "Firebase" and "ntfy", pick "ntfy"
3. "Push notification provider" setting now shows "Error" as current value, going back and then into "Advanced settings" again makes it switch back to "Firebase"

#### What did you expect?

It is possible to use ntfy as a push notification provider.

#### What happened instead?

Changing the provider to ntfy fails. Other apps like FediLab can register their ntfy topics without issue.

### Your phone model

Samsung S10

### Operating system version

LineageOS for microG 20

### Application version and app store

EXA 0.4.13

### Homeserver

xiretza.xyz, Synapse v1.105.1

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
OK, thanks for the issue and the log. If when you come back to the Advanced setting screen and see again "Firebase", it means that the unregistration of Firebase has failed. And indeed, I see in your log:

> java.lang.IllegalStateException: Unable to unregister pusher, Firebase token is not known.

The application should be lenient in this case I guess, I will create a PR.

**Comment by SpiritCroc** [comment]
There is another case which seems to fail currently, unrelated to the FCM provider:
```
2024-05-23T13:04:39.849665Z  WARN elementx: Failed to unregister previous push provider
java.lang.IllegalStateException: No endpoint or gateway found for client secret
	at io.element.android.libraries.pushproviders.unifiedpush.UnregisterUnifiedPushUseCase.execute-0E7RQCE(SourceFile:275)
	at io.element.android.libraries.pushproviders.unifiedpush.UnifiedPushProvider.unregister-gIAlu-s(SourceFile:95)
	at io.element.android.libraries.push.impl.DefaultPushService.registerWith-BWLJW6A(SourceFile:333)
	at io.element.android.features.preferences.impl.advanced.AdvancedSettingsPresenter$present$changePushProvider$1.invokeSuspend(SourceFile:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(SourceFile:7)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
 | 
```

Wondering if we just remove this line instead: https://github.com/SchildiChat/schildichat-android-next/blob/967b6889f6e05a8f4a0dbb9298cb800c3427ad9d/libraries/push/impl/src/main/kotlin/io/element/android/libraries/push/impl/DefaultPushService.kt#L73
Will let users test.
