### ISSUE TITLE
Crash while reporting logs

### ISSUE THREAD

**Issue by d4f5409d** [element-hq/element-x-android#3086]
### Steps to reproduce

1. Where are you starting? Crash report
2. What do you click? Send report
3. More steps… Experience crash

#### What did you expect?
Send the report
#### What happened instead?
Crash

### Your phone model

OnePlus 8

### Operating system version

Android 13

### Application version and app store

v.0.4.15

### Homeserver

Matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by d4f5409d** [comment]
Logs:
```kotlin
FATAL EXCEPTION: main
Process: io.element.android.x, PID: 21426
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1667)
	at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:436)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.writeInternal(ConscryptEngineSocket.java:704)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.write(ConscryptEngineSocket.java:699)
	at okio.OutputStreamSink.write(SourceFile:154)
	at okio.OutputStreamSink.write(SourceFile:67)
	at okio.RealBufferedSink.flush(SourceFile:19)
	at okhttp3.internal.http2.Http2Writer.rstStream(SourceFile:35)
	at okhttp3.internal.http2.Http2Stream.close(SourceFile:27)
	at okhttp3.internal.http2.Http2Stream.cancelStreamIfNecessary$okhttp(SourceFile:39)
	at okhttp3.internal.http2.Http2Stream$FramingSource.close(SourceFile:35)
	at okio.ForwardingSource.close(SourceFile:3)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.close(SourceFile:9)
	at okio.RealBufferedSource.close(SourceFile:10)
	at okio.RealBufferedSource.close(SourceFile:10)
	at okio.InflaterSource.close(SourceFile:16)
	at okio.GzipSource.close(SourceFile:3)
	at okio.RealBufferedSource.close(SourceFile:10)
	at okhttp3.internal.Util.closeQuietly(SourceFile:1)
	at okhttp3.ResponseBody.close(SourceFile:5)
	at okhttp3.Response.close(SourceFile:5)
	at io.element.android.features.rageshake.impl.reporter.DefaultBugReporter.sendBugReport(SourceFile:233)
	at io.element.android.features.rageshake.impl.reporter.DefaultBugReporter$sendBugReport$1.invokeSuspend(Unknown Source:18)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:113)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8423)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(ElementX Scope), StandaloneCoroutine{Cancelling}@ad89175, Dispatchers.Main]
```

**Comment by jmartinesp** [comment]
That's quite weird, I couldn't reproduce it even with strict mode enabled. I guess it might happen because the code tries to close the response stream in a coroutine running on the main dispatcher. I can change that, but I have no way of checking if it's actually fixed.

**Comment by d4f5409d** [comment]
Maybe it's a OnePlus thing. OnePlus is notorious for messing up their OS very bad.

**Comment by jmartinesp** [comment]
Hmm... I do have a OP device I can test this with. Thanks for the lead!

**Comment by d4f5409d** [comment]
> Hmm... I do have a OP device I can test this with. Thanks for the lead!
> 
> *EDIT:* it didn't fail on my OP11 either both with strict mode enabled and disabled.

Maybe thing I have de-googled.

**Comment by jmartinesp** [comment]
It would be nice to confirm if the issue is fixed for you by downloading https://github.com/element-hq/element-x-android/pull/3092#issuecomment-2188123191

And sending a test bug report from the onboarding screen using "Report a problem" at the bottom. That way we don't have to wait until the next nightly/release version to verify whether it's fixed or not.

Could you please test it?

**Comment by d4f5409d** [comment]
Yes, problem is resolved, however another one appeared: the app is lagging heavily. Chuncky framerate drops at all times.

**Comment by jmartinesp** [comment]
If you're using the build from the link I sent you, that's the debug build, which is quite slow because it contains lots of debugging info so I wouldn't recommend it for daily use. If you want to use a version with the fix you can always install tomorrow's nightly version once it's out, otherwise you'll have to wait until the next stable release.

**Comment by jmartinesp** [comment]
> I can wait. One more thing: it seems like I can't accept invites from grin.hu instance, EX throws me a server error. Can you look into it? I experience issues with nitro.chat instance as well as the keys are not coming and can't see encrypted messages from that instance.

Could you open a new issue with this info? It's way easier to track that way.

**Comment by d4f5409d** [comment]
> > I can wait. One more thing: it seems like I can't accept invites from grin.hu instance, EX throws me a server error. Can you look into it? I experience issues with nitro.chat instance as well as the keys are not coming and can't see encrypted messages from that instance.
> 
> Could you open a new issue with this info? It's way easier to track that way.

I hate creating new issues with templates (issue forms) because on phone we only can do this via browser but yeah, I'll do it 💀
