### ISSUE TITLE
Crash due to pinunlock activity

### ISSUE THREAD

**Issue by rei-zero246** [element-hq/element-x-android#3353]
### Steps to reproduce

1. Open the app. 
2. Watch it open and close. 

#### What did you expect?
The app to open. 

#### What happened instead?
It crashed. 

```
type: crash
osVersion: google/husky/husky:14/AP2A.240805.005/2024082200:user/release-keys
package: io.element.android.x:40005010
process: io.element.android.x
processUptime: 920 + 492 ms
installer: com.android.packageinstaller

java.lang.RuntimeException: Unable to start activity ComponentInfo{io.element.android.x/io.element.android.features.lockscreen.impl.unlock.activity.PinUnlockActivity}: java.lang.IllegalStateException: Unable to find bindings for io.element.android.features.lockscreen.impl.unlock.di.PinUnlockBindings
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4004)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4184)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2602)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.IllegalStateException: Unable to find bindings for io.element.android.features.lockscreen.impl.unlock.di.PinUnlockBindings
	at kotlin.LazyKt__LazyJVMKt.bindings(SourceFile:10)
	at io.element.android.features.lockscreen.impl.unlock.activity.PinUnlockActivity.onCreate(SourceFile:9)
	at android.app.Activity.performCreate(Activity.java:9013)
	at android.app.Activity.performCreate(Activity.java:8991)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1531)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3986)
	... 15 more
```

### Your phone model

Pixel 8 Pro

### Operating system version

Android 14

### Application version and app store

Element X 0.5.1

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by bmarty** [comment]
Thanks for reporting. I can repro on debug build, investigating.

**Comment by bmarty** [comment]
It looks ike this is coming from this change: https://github.com/element-hq/element-x-android/pull/3222/files#diff-480e88fdfc268ed708ace4cf328d417221f0baeea7afd86a4bc980949533b6ddR23.

Working on a fix.
